name: Testing CI

on:
  workflow_dispatch:
  push: 
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python 3.10 
      uses: actions/setup-python@v4
      with: 
        python-version: "3.10"

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Testting the application with pytest
      run: |
        python -m pytest --color=yes

    - name: Analysing the code with pylint
      run: |
        python -m pylint --exit-zero --color=yes $(git ls-files '*.py')
      
    - name: Analysing the tests covering
      run: |
        coverage run -m pytest --profile --color=yes
        coverage report -m

        